raft:
  node-urls:
    - http://localhost:8080
    - http://localhost:8081
    - http://localhost:8082
  command-timeout: 5s
  leader-cache-ttl: 10s

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    dev.pushkar.raft: INFO
