http-lab:
  base-url: http://localhost:8080
  connection-pool:
    max-connections: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: http-server-integration
