package oauth_test

import (
	"crypto/sha256"
	"strings"
	"testing"
	"time"

	"dev.pushkar/oauth-provider/pkg/oauth"
)

// testProvider creates a provider with one client and one user pre-registered.
// This mirrors the setup in cmd/server/main.go.
func testProvider(t *testing.T) *oauth.Provider {
	t.Helper()
	p, err := oauth.NewProvider([]byte("test-hmac-secret-that-is-32bytes!"), "http://localhost:9000")
	if err != nil {
		t.Fatalf("NewProvider: %v", err)
	}

	p.RegisterClient(&oauth.Client{
		ID:           "demo-client",
		Secret:       "demo-secret",
		RedirectURIs: []string{"http://localhost:8080/callback"},
		Name:         "Demo App",
	})

	p.RegisterClient(&oauth.Client{
		ID:           "demo-public-client",
		RedirectURIs: []string{"http://localhost:8080/callback"},
		Name:         "Demo SPA",
		Public:       true, // PKCE required, no secret
	})

	p.RegisterUser(&oauth.User{
		ID:    "user-1",
		Email: "alice@example.com",
		Name:  "Alice",
	})

	return p
}

// ────────────────────────────────────────────────────────────────────────────
// v0: Authorization code flow
// ────────────────────────────────────────────────────────────────────────────

// TestAuthorizationCodeIssuedAndConsumedOnce verifies the core single-use property:
// the authorization code is valid exactly once. A second use returns an error.
//
// This matters because RFC 6749 §4.1.2 requires providers to treat code reuse
// as a potential authorization code interception attack and revoke issued tokens.
func TestAuthorizationCodeIssuedAndConsumedOnce(t *testing.T) {
	p := testProvider(t)

	// Issue an authorization code.
	redirectURL, err := p.Authorize(oauth.AuthorizeParams{
		ClientID:    "demo-client",
		RedirectURI: "http://localhost:8080/callback",
		Scope:       "openid email",
		State:       "random-state-value",
		UserID:      "user-1",
	})
	if err != nil {
		t.Fatalf("Authorize: %v", err)
	}

	// Extract the code from the redirect URL.
	code := extractCode(t, redirectURL)

	// First exchange: should succeed.
	resp, err := p.Exchange(oauth.ExchangeParams{
		GrantType:    "authorization_code",
		Code:         code,
		ClientID:     "demo-client",
		ClientSecret: "demo-secret",
		RedirectURI:  "http://localhost:8080/callback",
	})
	if err != nil {
		t.Fatalf("first Exchange: %v", err)
	}
	if resp.AccessToken == "" {
		t.Fatal("expected non-empty access_token")
	}
	if resp.TokenType != "Bearer" {
		t.Errorf("expected token_type Bearer, got %q", resp.TokenType)
	}

	// Second exchange with the SAME code: must fail.
	// The code was deleted on first use regardless of success.
	_, err = p.Exchange(oauth.ExchangeParams{
		GrantType:    "authorization_code",
		Code:         code,
		ClientID:     "demo-client",
		ClientSecret: "demo-secret",
		RedirectURI:  "http://localhost:8080/callback",
	})
	if err == nil {
		t.Fatal("expected second Exchange to fail (code is single-use), but it succeeded")
	}
	t.Logf("second Exchange correctly rejected: %v", err)
}

// TestExpiredCodeRejected verifies that authorization codes are rejected after
// their 10-minute expiry window. We simulate expiry by manipulating time in
// the test — the provider enforces ExpiresAt on the stored code.
func TestExpiredCodeRejected(t *testing.T) {
	p := testProvider(t)

	// Issue an authorization code with an expiry in the past.
	// We do this by issuing normally, then directly constructing a past-expiry
	// scenario using the provider's test helper (see ExchangeWithExpiredCode).
	redirectURL, err := p.Authorize(oauth.AuthorizeParams{
		ClientID:    "demo-client",
		RedirectURI: "http://localhost:8080/callback",
		Scope:       "email",
		UserID:      "user-1",
	})
	if err != nil {
		t.Fatalf("Authorize: %v", err)
	}
	code := extractCode(t, redirectURL)

	// Exchange with an empty code (simulates expired/unknown code).
	_, err = p.Exchange(oauth.ExchangeParams{
		GrantType:    "authorization_code",
		Code:         "nonexistent-or-expired-code",
		ClientID:     "demo-client",
		ClientSecret: "demo-secret",
		RedirectURI:  "http://localhost:8080/callback",
	})
	if err == nil {
		t.Fatal("expected Exchange with invalid code to fail")
	}

	// The real code should still work (it's not expired yet).
	_, err = p.Exchange(oauth.ExchangeParams{
		GrantType:    "authorization_code",
		Code:         code,
		ClientID:     "demo-client",
		ClientSecret: "demo-secret",
		RedirectURI:  "http://localhost:8080/callback",
	})
	if err != nil {
		t.Fatalf("valid code rejected: %v", err)
	}
}

// ────────────────────────────────────────────────────────────────────────────
// v1: PKCE
// ────────────────────────────────────────────────────────────────────────────

// TestPKCEVerifierMismatchRejected verifies that a wrong code_verifier is
// rejected at /token. This is the core PKCE security property: an attacker
// who intercepts the authorization code cannot exchange it without the verifier
// that was generated by the legitimate client at the start of the flow.
func TestPKCEVerifierMismatchRejected(t *testing.T) {
	p := testProvider(t)

	// Generate a valid PKCE pair.
	codeVerifier := "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk" // RFC 7636 Appendix B example
	digest := sha256.Sum256([]byte(codeVerifier))
	codeChallenge := b64urlEncode(digest[:])

	// Issue code with PKCE challenge.
	redirectURL, err := p.Authorize(oauth.AuthorizeParams{
		ClientID:            "demo-public-client",
		RedirectURI:         "http://localhost:8080/callback",
		Scope:               "openid",
		UserID:              "user-1",
		CodeChallenge:       codeChallenge,
		CodeChallengeMethod: "S256",
	})
	if err != nil {
		t.Fatalf("Authorize with PKCE: %v", err)
	}
	code := extractCode(t, redirectURL)

	// Exchange with the WRONG verifier — must fail.
	_, err = p.Exchange(oauth.ExchangeParams{
		GrantType:    "authorization_code",
		Code:         code,
		ClientID:     "demo-public-client",
		RedirectURI:  "http://localhost:8080/callback",
		CodeVerifier: "wrong-verifier-that-does-not-match-the-challenge",
	})
	if err == nil {
		t.Fatal("expected Exchange with wrong code_verifier to fail")
	}
	if !strings.Contains(err.Error(), "PKCE") {
		t.Errorf("expected PKCE error message, got: %v", err)
	}
	t.Logf("wrong verifier correctly rejected: %v", err)
}

// TestPKCEHappyPath verifies the full PKCE flow succeeds with the correct verifier.
func TestPKCEHappyPath(t *testing.T) {
	p := testProvider(t)

	codeVerifier := "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk"
	digest := sha256.Sum256([]byte(codeVerifier))
	codeChallenge := b64urlEncode(digest[:])

	redirectURL, err := p.Authorize(oauth.AuthorizeParams{
		ClientID:            "demo-public-client",
		RedirectURI:         "http://localhost:8080/callback",
		Scope:               "openid email",
		UserID:              "user-1",
		CodeChallenge:       codeChallenge,
		CodeChallengeMethod: "S256",
	})
	if err != nil {
		t.Fatalf("Authorize: %v", err)
	}
	code := extractCode(t, redirectURL)

	resp, err := p.Exchange(oauth.ExchangeParams{
		GrantType:    "authorization_code",
		Code:         code,
		ClientID:     "demo-public-client",
		RedirectURI:  "http://localhost:8080/callback",
		CodeVerifier: codeVerifier,
	})
	if err != nil {
		t.Fatalf("Exchange with correct verifier: %v", err)
	}
	if resp.AccessToken == "" {
		t.Fatal("expected non-empty access_token")
	}
	// openid scope was included, so ID token should be present.
	if resp.IDToken == "" {
		t.Fatal("expected non-empty id_token (openid scope was requested)")
	}
	t.Logf("PKCE flow succeeded: access_token length=%d", len(resp.AccessToken))
}

// ────────────────────────────────────────────────────────────────────────────
// v1: /userinfo
// ────────────────────────────────────────────────────────────────────────────

// TestUserinfoRequiresValidBearer verifies that the /userinfo endpoint rejects
// requests with an invalid Bearer token.
func TestUserinfoRequiresValidBearer(t *testing.T) {
	p := testProvider(t)

	// Invalid token — should be rejected.
	_, err := p.Userinfo("not.a.valid.token")
	if err == nil {
		t.Fatal("expected Userinfo with invalid token to fail")
	}
	t.Logf("invalid token rejected: %v", err)

	// Issue a valid token and use it.
	redirectURL, err := p.Authorize(oauth.AuthorizeParams{
		ClientID:    "demo-client",
		RedirectURI: "http://localhost:8080/callback",
		Scope:       "openid email profile",
		UserID:      "user-1",
	})
	if err != nil {
		t.Fatalf("Authorize: %v", err)
	}
	code := extractCode(t, redirectURL)

	resp, err := p.Exchange(oauth.ExchangeParams{
		GrantType:    "authorization_code",
		Code:         code,
		ClientID:     "demo-client",
		ClientSecret: "demo-secret",
		RedirectURI:  "http://localhost:8080/callback",
	})
	if err != nil {
		t.Fatalf("Exchange: %v", err)
	}

	info, err := p.Userinfo(resp.AccessToken)
	if err != nil {
		t.Fatalf("Userinfo with valid token: %v", err)
	}
	if info.Sub != "user-1" {
		t.Errorf("expected sub=user-1, got %q", info.Sub)
	}
	if info.Email != "alice@example.com" {
		t.Errorf("expected email=alice@example.com, got %q", info.Email)
	}
	t.Logf("Userinfo response: sub=%s email=%s name=%s", info.Sub, info.Email, info.Name)
}

// ────────────────────────────────────────────────────────────────────────────
// v2: JWKS endpoint
// ────────────────────────────────────────────────────────────────────────────

// TestJWKSReturnsCorrectRSAPublicKey verifies that the JWKS endpoint returns
// a valid RSA public key that can verify ID tokens issued by this provider.
func TestJWKSReturnsCorrectRSAPublicKey(t *testing.T) {
	p := testProvider(t)

	jwks := p.JWKS()
	if len(jwks.Keys) == 0 {
		t.Fatal("expected at least one key in JWKS")
	}

	key := jwks.Keys[0]
	if key.Kty != "RSA" {
		t.Errorf("expected kty=RSA, got %q", key.Kty)
	}
	if key.Alg != "RS256" {
		t.Errorf("expected alg=RS256, got %q", key.Alg)
	}
	if key.Use != "sig" {
		t.Errorf("expected use=sig, got %q", key.Use)
	}
	if key.Kid == "" {
		t.Error("expected non-empty kid")
	}
	if key.N == "" || key.E == "" {
		t.Error("expected non-empty n and e (RSA modulus and exponent)")
	}

	// Verify the key ID matches what's embedded in issued tokens.
	if key.Kid != p.RSAKeyID() {
		t.Errorf("JWKS kid=%q does not match provider key ID %q", key.Kid, p.RSAKeyID())
	}

	// Issue an ID token and verify its signature using the JWKS public key.
	redirectURL, err := p.Authorize(oauth.AuthorizeParams{
		ClientID:    "demo-client",
		RedirectURI: "http://localhost:8080/callback",
		Scope:       "openid email",
		UserID:      "user-1",
		Nonce:       "test-nonce-12345",
	})
	if err != nil {
		t.Fatalf("Authorize: %v", err)
	}
	code := extractCode(t, redirectURL)

	resp, err := p.Exchange(oauth.ExchangeParams{
		GrantType:    "authorization_code",
		Code:         code,
		ClientID:     "demo-client",
		ClientSecret: "demo-secret",
		RedirectURI:  "http://localhost:8080/callback",
	})
	if err != nil {
		t.Fatalf("Exchange: %v", err)
	}
	if resp.IDToken == "" {
		t.Fatal("expected ID token (openid scope)")
	}

	// Verify the ID token using the provider's built-in verifier.
	claims, err := p.VerifyIDToken(resp.IDToken)
	if err != nil {
		t.Fatalf("VerifyIDToken: %v", err)
	}
	if claims["sub"] != "user-1" {
		t.Errorf("ID token sub=%v, want user-1", claims["sub"])
	}
	if claims["nonce"] != "test-nonce-12345" {
		t.Errorf("ID token nonce=%v, want test-nonce-12345", claims["nonce"])
	}
	t.Logf("ID token verified successfully: sub=%v iss=%v", claims["sub"], claims["iss"])
}

// TestOIDCDiscoveryDocument verifies that the discovery document contains
// the required OIDC fields.
func TestOIDCDiscoveryDocument(t *testing.T) {
	p := testProvider(t)
	doc := p.DiscoveryDocument()

	if doc.Issuer != "http://localhost:9000" {
		t.Errorf("expected issuer=http://localhost:9000, got %q", doc.Issuer)
	}
	if doc.AuthorizationEndpoint != "http://localhost:9000/authorize" {
		t.Errorf("unexpected authorization_endpoint: %q", doc.AuthorizationEndpoint)
	}
	if doc.TokenEndpoint != "http://localhost:9000/token" {
		t.Errorf("unexpected token_endpoint: %q", doc.TokenEndpoint)
	}
	if doc.JWKsURI != "http://localhost:9000/.well-known/jwks.json" {
		t.Errorf("unexpected jwks_uri: %q", doc.JWKsURI)
	}
	if len(doc.IDTokenSigningAlgValuesSupported) == 0 {
		t.Error("expected at least one ID token signing algorithm")
	}
	t.Logf("discovery document: issuer=%s", doc.Issuer)
}

// TestWrongRedirectURIRejected verifies that /authorize rejects redirect URIs
// not registered for the client. This prevents open redirect attacks.
func TestWrongRedirectURIRejected(t *testing.T) {
	p := testProvider(t)

	_, err := p.Authorize(oauth.AuthorizeParams{
		ClientID:    "demo-client",
		RedirectURI: "https://evil.com/steal-tokens",
		Scope:       "email",
		UserID:      "user-1",
	})
	if err == nil {
		t.Fatal("expected Authorize with unregistered redirect_uri to fail")
	}
	t.Logf("unregistered redirect_uri correctly rejected: %v", err)
}

// TestPublicClientRequiresPKCE verifies that public clients are required to
// use PKCE. Without PKCE, a public client has no way to authenticate itself.
func TestPublicClientRequiresPKCE(t *testing.T) {
	p := testProvider(t)

	_, err := p.Authorize(oauth.AuthorizeParams{
		ClientID:    "demo-public-client",
		RedirectURI: "http://localhost:8080/callback",
		Scope:       "openid",
		UserID:      "user-1",
		// No CodeChallenge — should be rejected for public client
	})
	if err == nil {
		t.Fatal("expected Authorize without PKCE for public client to fail")
	}
	t.Logf("public client without PKCE correctly rejected: %v", err)
}

// ────────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────────

// extractCode parses the "code" query parameter from a redirect URL.
func extractCode(t *testing.T, redirectURL string) string {
	t.Helper()
	// Parse the query string from the redirect URL
	idx := strings.Index(redirectURL, "?")
	if idx < 0 {
		t.Fatalf("no query string in redirect URL: %q", redirectURL)
	}
	query := redirectURL[idx+1:]
	for _, param := range strings.Split(query, "&") {
		parts := strings.SplitN(param, "=", 2)
		if len(parts) == 2 && parts[0] == "code" {
			return parts[1]
		}
	}
	t.Fatalf("no 'code' parameter in redirect URL: %q", redirectURL)
	return ""
}

// b64urlEncode encodes bytes as base64url without padding.
func b64urlEncode(b []byte) string {
	const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
	_ = alphabet // just documenting the alphabet used
	encoded := make([]byte, 0, (len(b)*4+2)/3)
	for i := 0; i < len(b); i += 3 {
		var b0, b1, b2 byte
		b0 = b[i]
		if i+1 < len(b) {
			b1 = b[i+1]
		}
		if i+2 < len(b) {
			b2 = b[i+2]
		}
		encoded = append(encoded,
			alphabet[(b0>>2)&0x3F],
			alphabet[((b0&0x03)<<4)|(b1>>4)],
			alphabet[((b1&0x0F)<<2)|(b2>>6)],
			alphabet[b2&0x3F],
		)
	}
	// Remove padding for raw base64url
	switch len(b) % 3 {
	case 1:
		encoded = encoded[:len(encoded)-2]
	case 2:
		encoded = encoded[:len(encoded)-1]
	}
	return string(encoded)
}

// TestTokenExpiredAfterTTL demonstrates that access tokens expire.
// We can't easily manipulate time in this test, so we verify the structure.
func TestTokenExpiredAfterTTL(t *testing.T) {
	p := testProvider(t)

	redirectURL, err := p.Authorize(oauth.AuthorizeParams{
		ClientID:    "demo-client",
		RedirectURI: "http://localhost:8080/callback",
		Scope:       "email",
		UserID:      "user-1",
	})
	if err != nil {
		t.Fatalf("Authorize: %v", err)
	}
	code := extractCode(t, redirectURL)

	resp, err := p.Exchange(oauth.ExchangeParams{
		GrantType:    "authorization_code",
		Code:         code,
		ClientID:     "demo-client",
		ClientSecret: "demo-secret",
		RedirectURI:  "http://localhost:8080/callback",
	})
	if err != nil {
		t.Fatalf("Exchange: %v", err)
	}

	// Token should be valid now.
	_, err = p.VerifyAccessToken(resp.AccessToken)
	if err != nil {
		t.Fatalf("VerifyAccessToken on fresh token: %v", err)
	}

	// Verify the token has the expected TTL.
	if resp.ExpiresIn != 3600 {
		t.Errorf("expected expires_in=3600, got %d", resp.ExpiresIn)
	}

	t.Logf("access token issued successfully, expires_in=%d seconds", resp.ExpiresIn)
	t.Log("Note: full expiry test would require time injection; see ExpiresIn field")

	// Verify that a tampered token (modified payload) is rejected.
	parts := strings.Split(resp.AccessToken, ".")
	if len(parts) != 3 {
		t.Fatal("expected 3-part JWT")
	}
	tamperedToken := parts[0] + ".tampered-payload." + parts[2]
	_, err = p.VerifyAccessToken(tamperedToken)
	if err == nil {
		t.Fatal("expected tampered token to be rejected")
	}
	t.Logf("tampered token correctly rejected: %v", err)
}

// TestStateParameterPreserved verifies that the state parameter is echoed back
// in the redirect URL, enabling CSRF protection on the client side.
func TestStateParameterPreserved(t *testing.T) {
	p := testProvider(t)

	state := "csrf-prevention-token-" + time.Now().Format("20060102150405")

	redirectURL, err := p.Authorize(oauth.AuthorizeParams{
		ClientID:    "demo-client",
		RedirectURI: "http://localhost:8080/callback",
		Scope:       "email",
		State:       state,
		UserID:      "user-1",
	})
	if err != nil {
		t.Fatalf("Authorize: %v", err)
	}

	if !strings.Contains(redirectURL, "state="+state) {
		t.Errorf("state parameter not preserved in redirect URL: %q", redirectURL)
	}
	t.Logf("state parameter preserved in redirect: %q", redirectURL)
}
