spring.application.name=garbage-collector-gc-demo
# Suppress Spring Boot banner and reduce noise
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.dev.pushkar=INFO

# GC demo config
gc.demo-allocations=50000
gc.jfr-enabled=false
