queue:
  base-url: http://localhost:8080
  default-queue-name: default
  default-visibility-timeout-sec: 30
  max-messages: 10

spring:
  application:
    name: message-queue-demo

management:
  endpoints:
    web:
      exposure:
        include: health,info
